### ISSUE TITLE
New lighthouse performance score

### ISSUE THREAD

**Issue by franklinjavier** [vercel/vrs#10]
Hi, I think it need some work to get 100% of performance score from lighthouse, as you can see below

/about [lighthouse](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https://serverless-vrs.now.sh/about)
![image](https://user-images.githubusercontent.com/440220/71946032-4bd87d80-31a7-11ea-8a57-4e0343852d54.png)

/store [lighthouse](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https://serverless-vrs.now.sh/store)
![image](https://user-images.githubusercontent.com/440220/71946149-bee1f400-31a7-11ea-8295-26512c941a39.png)

**Comment by leerob** [comment]
Closing as won't fix. Thank you for reporting 🙏
